ARG VERSION=latest
FROM prom/prometheus:${VERSION}
COPY --chown=nobody:nogroup prom.yml /etc/prometheus/prom.yml
EXPOSE 9090
CMD ["--config.file=/etc/prometheus/prom.yml","--storage.tsdb.path=/prometheus"]
